version: '3'
services:
    db:
        image: 'postgres:13'
        restart: unless-stopped
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./db-data:/var/lib/postgresql/data/

    worker:
        image: 'ptrxyz/chemotion:1.0.3D0.1'
        restart: unless-stopped
        command: ["starteln"]
        environment:
            - CONFIG_ROLE="worker"
        depends_on:
            - 'db'
        volumes:
            - ./shared:/shared

    eln:
        image: 'ptrxyz/chemotion:1.0.3D0.1'
        restart: unless-stopped
        command: ["starteln"]
        depends_on:
            - 'db'
        expose:
            - '4000'
        ports:
            - 4000:4000
        volumes:
            - ./shared:/shared

    msconvert:
        image: chambm/pwiz-skyline-i-agree-to-the-vendor-licenses
        container_name: msconvert
        expose:
            - 8088
        ports:
            - 8088:8088
        volumes:
            - ${PWD}/spectra-shared:/data:rw
            - ${PWD}/scripts/dist/flaskrun35:/bin/mscrun:ro
            - ${PWD}/scripts/mscrunner.py:/bin/mscrunner.py:ro
        entrypoint: /bin/mscrun /bin/mscrunner.py
        environment:
            WINEDEBUG: '-all'
            MSC_PORT: '8088'
        stop_signal: SIGINT

    spectra:
        image: ptrxyz/spectra-app:21.05-1
        depends_on:
            - msconvert
        ports:
            - 3007:3007
        volumes:
            - ${PWD}/spectra_config.py:/app/instance/config.py:ro
            - ${PWD}/spectra-shared:/shared:rw
        restart: unless-stopped
        stop_signal: SIGINT
        environment:
            FLASK_ENV: 'production'
            MSC_HOST: 'msconvert'
            MSC_PORT: '8088'
            MSC_VALIDATE: 'true'
            SHARE: ${PWD}/spectra-shared