# This is a basic workflow to help you get started with Actions

name: generateTestData

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd $GITHUB_WORKSPACE
          ls
          echo -- creating folder db-data
          mkdir db-data
          ls
          cd shared/eln/
          ls
          echo -- Unpacking app.tar.gz
          tar xfz app.tar.gz
          rm app.tar.gz
          echo -- app.tar.gz unpacked.
          echo -- Unpacking config.tar.gz
          tar xfz config.tar.gz
          rm config.tar.gz
          echo -- config.tar.gz unpacked.
          echo -- Unpacking log.tar.gz
          tar xfz log.tar.gz
          rm log.tar.gz
          echo -- log.tar.gz unpacked.
          echo -- Unpacking public.tar.gz
          tar xfz public.tar.gz
          rm public.tar.gz
          echo -- public.tar.gz unpacked.
          echo -- Unpacking tmp.tar.gz
          tar xfz tmp.tar.gz
          rm tmp.tar.gz
          echo -- tmp.tar.gz unpacked.
          echo -- Unpacking uploads.tar.gz
          tar xfz uploads.tar.gz
          rm uploads.tar.gz
          echo -- uploads.tar.gz unpacked.
          ls
          cd ../..
          ls
          mkdir -p spectra-shared
          yes yes | docker-compose run --service-ports eln init
          docker-compose up -d
          sleep 30
          curl -L localhost:4000 | tail -5 | head -1
          cd seleniumTests/Tests/
          sudo apt -y install python3-selenium firefox-geckodriver
          python3 userManagement.py